apiVersion: v1
kind: Service
metadata:
  name: kubix-service
spec:
  selector:
    app: kubix
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30000