apiVersion: apps/v1
kind: Deployment
metadata:
  name: elixir
  namespace: default
  labels:
    app: kubix
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubix
  template:
    metadata:
      labels:
        app: kubix
        tier: web
    spec:
      containers:
      - name: kubix
        image: docker.io/adrianpaulcarrieres/kubix2:2.3
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        envFrom:
          - secretRef:
              name: elixir-secret
          - configMapRef:
              name: elixir-configmap
          - configMapRef:
              name: postgres-configmap
          - secretRef:
              name: postgres-secret
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
                fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      imagePullSecrets:
        - name: regcred